services:

  neo4j:
    image: "neo4j:community-ubi9"
    hostname: neo4j
    container_name: neo4j
    volumes:
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/config:/config
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/plugins:/plugins
      - ./data/output/done/graph:/import
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    secrets:
      - neo4j_auth_file

  app:
    build: .
    hostname: app
    container_name: app
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
      - NEO4J_URI="neo4j://neo4j"
    secrets:
      - neo4j_auth_file
    depends_on:
      - neo4j

secrets:
  neo4j_auth_file:
    file: ./neo4j_auth_dev.txt