execution_environment:
   local:
          data_origin: 'csv'
          data_directory_path:
              base_path: ../data
              data:
                  input:
                      base_path: input
                      directories:
                            - inbound
                            - work
                  output:
                      base_path: output
                      directories:
                            - error
                            - done
                  file_type:
                    - type: clinical_trials
                      file_regex: "^clinial_trials[.](?P<ext>csv|json)$"
                    - type: drugs
                      file_regex: "^drugs[.](?P<ext>csv|json)$"
                    - type: pubmed
                      file_regex: "^pubmed[.](?P<ext>csv|json)$"
              config:
                  directories:
                      config: config
                      flows: flows
                  files:
                      logger_config: logger_config.yaml
                      flows: flows.yaml